# See https://docs.docker.com/compose/compose-file/compose-file-v3/
version: "3.9"

services:
  # Backend Service
  backend:
    container_name: time-bucket-backend
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
#    env_file:
#      - ./backend/.env
    ports:
      - "8080:8080"
    volumes:
      # Bind package directory with volume because speeding up.
      - go-packages:/go
      - ./backend/src:/work
  db:
    container_name: time-bucket-db
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app

volumes:
  go-packages:
  node-packages:
  db-data:
