SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `bucket_items`;
CREATE TABLE IF NOT EXISTS `bucket_items` (
    `id` VARCHAR(26) NOT NULL COMMENT 'ID',
    `name` VARCHAR(255) NOT NULL COMMENT '名前',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COMMENT="タイムバケットのアイテム";